### ISSUE TITLE
Can't import TMAG5273_unit.zip

### ISSUE THREAD

**Issue by udu3324** [TuYuxiao/TMAG5273#3]
Hello. I've tried downloading [jialichuang EDA](https://lceda.cn/) to import/look at TMAG5273_unit.zip but couldn't because I am in North America, and the servers are too far away. 
Could you please post screenshots of schematics and the design here please? I am interested in them.

**Comment by TuYuxiao** [comment]
[TMAG5273_unit_PCB.pdf](https://github.com/TuYuxiao/TMAG5273/files/12334432/TMAG5273_unit_PCB.pdf)
[TMAG5273_unit_SCH.pdf](https://github.com/TuYuxiao/TMAG5273/files/12334433/TMAG5273_unit_SCH.pdf)
